---
circle_ipa_realm: "CCLINUX.ORG"
circle_ldap_bind_dn: "uid=binder,cn=sysaccounts,cn=etc,dc=cclinux,dc=org"
circle_ldap_user_basedn: "cn=users,cn=accounts,dc=cclinux,dc=org"
circle_ldap_group_basedn: "cn=groups,cn=accounts,dc=cclinux,dc=org"
circle_ldap_account_basedn: "cn=accounts,dc=cclinux,dc=org"
# Requires jinja 2.9+
circle_ipaserver_list: "{{ groups['ipaserver'] + groups['ipareplicas'] }}"
circle_ipaserver_lb: "ipa-lb.cclinux.org"
# This will need to be vaulted
circle_ldap_bind_pw: "{{ ipa_binder_password }}"
