---
# Sigul Bridge Variables
sigul_type: bridge
sigul_ipa_realm: "CCLINUX.ORG"
sigul_bridge_cert_nickname: "sigul-bridge"
sigul_principal: "sigul/sigul.cclinux.org@{{ sigul_ipa_realm }}"
sigul_keytab: /etc/sigul.keytab
sigul_nss_dir: /etc/pki/tls/sigul

# ipa-getcert variables
ipa_getcert_nss: true
ipa_getcert_requested_hostnames:
  - name: "{{ ansible_fqdn }}"
    owner: sigul
    nss_db_dir: "{{ sigul_nss_dir }}"
    nss_nickname: "{{ sigul_bridge_cert_nickname }}"
