---
# vars for kojid

kojid_vendor: Circle
kojid_packager: infrastructure@cclinux.org
kojid_distribution: Circle
# These three should probably be specified by special vars
# kojid_web_url: https://koji.cclinux.org/koji
# kojid_hub_url: https://koji.cclinux.org/kojihub
# kojid_files_url: https://koji.cclinux.org/kojifiles

kojid_ca_bundle: /etc/pki/tls/certs/ca-bundle.crt
kojid_keytab: /etc/kojid.keytab
kojid_smtp_host: smtp.cclinux.org
kojid_allowed_scm: "git.centos.org:/* git.cclinux.org:/*"
