---
# Currently only one SUDO role should be created, and that is for the
# circle linux admins
- name: "Creating SUDO Role for Circle Admins"
  freeipa.ansible_freeipa.ipasudorule:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: All_CircleAdmins
    description: Circle Linux infrastructure and operations sudo access
    group:
      - circleadm
    hostcat: all
    cmdcat: all
