---
# Init koji
- name: kinit as koji admin using password
  shell: "set -o pipefail && echo \"{{ circlekoji_password }}\" | kinit circlekoji@CCLINUX.ORG"
  check_mode: false
  changed_when: "1 != 1"
  become: yes
  become_user: koji
  when: circlekoji_has_password | bool

- name: kinit as koji admin using keytab
  shell: "set -o pipefail && kinit -kt /home/koji/.koji/keytab koji/circlekoji@CCLINUX.ORG"
  check_mode: false
  changed_when: "1 != 1"
  become: yes
  become_user: koji
  when: not circlekoji_has_password | bool

- name: Import current necessary tags
  shell: "set -o pipefail && koji add-tag {{ item }}"
  changed_when: "1 != 1"
  become: yes
  become_user: koji
  loop:
    - build-modules
    - dist-circle8
    - dist-circle8-build
    - dist-circle8-compose
    - dist-circle8-extras
    - dist-circle8-gcc-toolset-9-build
    - dist-circle8-modular-buildrequires
    - dist-circle8-module-compose
    - dist-circle8-plus
    - dist-circle8-rust-bootstrap
    - dist-circle8-rust-bootstrap-build
    - dist-circle8-updates
    - dist-circle8-updates-build
    - dist-circle8_0-updates-build
    - dist-circle8_1-gcc-toolset-9-build
    - dist-circle8_1-updates-build
    - dist-circle8_2-updates-build
    - dist-circle8_3-updates-build
    - dist-circle8_4-updates-build
    - dist-circle9
    - el8
    - el8_0
    - el8_1
    - el8_2
    - el8_3
    - el8_4
    - el8_infra
    - el9
    - el9_infra
    - eln
    - modular-updates-candidate
    - module-circle-8.0.0-build
    - module-circle-8.1.0-build
    - module-circle-8.2.0-build
    - module-circle-8.3.0-build
    - module-circle-8.4.0-build
    - trash
    - trashcan
